@echo off

cd "%CD%\configuration-server"
mvn "clean" "package" "-DskipTests"
cd "%CD%."
cd "%CD%\auth-server"
mvn "clean" "package" "-DskipTests"
cd "%CD%."
cd "%CD%\discovery-server"
mvn "clean" "package" "-DskipTests"
cd "%CD%."
cd "%CD%\gateway-service"
mvn "clean" "package" "-DskipTests"
cd "%CD%."
cd "%CD%\professor-service"
mvn "clean" "package" "-DskipTests"
cd "%CD%."
cd "%CD%\student-service"
mvn "clean" "package" "-DskipTests"
cd "%CD%."
cd "%CD%\evaluation-service"
mvn "clean" "package" "-DskipTests"
cd "%CD%."
cd "%CD%\notification-service"
mvn "clean" "package" "-DskipTests"
cd "%CD%."
cd "%CD%\course-service"
mvn "clean" "package" "-DskipTests"
