server:
  port: 9000


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
spring:
  data:
    mongodb:
      uri: mongodb+srv://ikub:ikub123@bulding-cluster.ltijm.mongodb.net/?retryWrites=true&w=majority
      database: user-db
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://zipkin:9411
  application:
    name: auth-server


registeredClient:
  clientId: ikub
  clientSecret: secret
  redirectUri: http://172.17.0.1:4200/authorized
  issuerUri: http://localhost:9000
  tokenParam: id_token
  roleClaim: authorities

--- 

server:
  port: 9000
  
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
spring:
  application:
    name: auth-server
  data:
    mongodb:
      uri: mongodb+srv://ikub:ikub123@bulding-cluster.ltijm.mongodb.net/?retryWrites=true&w=majority
      database: user-db
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: docker
  zipkin:
    base-url: http://zipkin:9411



registeredClient:
  clientId: ikub
  clientSecret: secret
  redirectUri: http://172.17.0.1:4200/authorized
  issuerUri: http://auth-server:9000
  tokenParam: id_token
  roleClaim: authorities
