server:
  port: 9999
spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GretiCani/grading-config-repo
          username: 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
          password: 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
          timeout: 10
          default-label: core
        bootstrap: true