server:
  port: 9999
spring:
  application:
    name: configuration-server
  profiles:
    active: native
  zipkin:
    base-url: http://localhost:9411
  cloud:
    config:
      server:
        native:
          search-locations: src/main/resources/config
        bootstrap: true
