version: '3.7'

services:

  prometheus:
    image: prom/prometheus
    container_name: 'prometheus'
    hostname: prometheus
    ports:
      - '9090:9090'
    networks:
      - dev_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # - prometheus_data:/prometheus-data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: 'grafana'
    hostname: grafana
    networks:
      - dev_network
    ports:
      - '3000:3000'
    volumes:
      - grafana_data 
    # env_file:
    #   - grafana/config.monitoring
    depends_on:
      - prometheus

networks:
  dev_network:
    external: true
     

volumes:
  grafana_data: {}