version: '3.7'

services:

  # configuration-server:
  #   build:
  #     context: ../configuration-server
  #     dockerfile: Dockerfile
  #   networks:
  #     -   dev_network
  #   ports:
  #     - 9999:9999

  eureka-server:
    build:
      context: ../discovery-server
      dockerfile: Dockerfile
    networks:
      - dev_network
    ports:
      - 8080:8080


  gateway-service:
    build:
      context: ../gateway-service
      dockerfile: Dockerfile
    networks:
      -   dev_network
    ports:
      - 8081:8081
    
    depends_on:
      - eureka-server

  professor-service:
    build:
      context: ../professor-service
      dockerfile: Dockerfile
    networks:
      - dev_network
    
    depends_on:
      - eureka-server
      - gateway-service
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  
  student-service:
    build:
      context: ../student-service
      dockerfile: Dockerfile
    networks:
      - dev_network
    
    depends_on:
      - eureka-server
      - gateway-service

  evaluation-service:
    build:
      context: ../evaluation-service
      dockerfile: Dockerfile
    networks:
      - dev_network
    
    depends_on:
      - eureka-server
      - gateway-service

  notification-service:
    build:
      context: ../notification-service
      dockerfile: Dockerfile
    networks:
      - dev_network
    
    depends_on:
      - eureka-server
      - gateway-service

  course-service:
    build:
      context: ../course-service
      dockerfile: Dockerfile
    networks:
      - dev_network
    
    depends_on:
      - eureka-server
      - gateway-service
      
networks:
  dev_network:
    external: true
     


      