version: '3.7'

services:

  gateway-service:
    build:
      context: ../gateway-service
      dockerfile: Dockerfile
    networks:
      -   dev_network
    ports:
      - 8081:8081
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  professor-service:
    build:
      context: ../professor-service
      dockerfile: Dockerfile
    networks:
      - dev_network
    depends_on:
      - gateway-service
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  
  student-service:
    build:
      context: ../student-service
      dockerfile: Dockerfile
    networks:
      - dev_network
    
    depends_on:
      - gateway-service
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  evaluation-service:
    build:
      context: ../evaluation-service
      dockerfile: Dockerfile
    networks:
      - dev_network
    
    depends_on:
      - gateway-service
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  notification-service:
    build:
      context: ../notification-service
      dockerfile: Dockerfile
    networks:
      - dev_network
    
    depends_on:
      - gateway-service
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  course-service:
    build:
      context: ../course-service
      dockerfile: Dockerfile
    networks:
      - dev_network
    
    depends_on:
      - gateway-service
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
      
networks:
  dev_network:
    external: true
     


      