version: '3.7'

services:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: always
    networks:
      - dev_network

  auth-server:
    build:
      context: ../auth-server
      dockerfile: Dockerfile
    networks:
      -   dev_network
    ports:
      - 9000:9000

  configuration-server:
    build:
      context: ../configuration-server
      dockerfile: Dockerfile
    networks:
      -   dev_network
    ports:
      - 9999:9999

  eureka-server:
    build:
      context: ../discovery-server
      dockerfile: Dockerfile
    networks:
      - dev_network
    ports:
      - 8080:8080
    depends_on:
      - configuration-server
      
networks:
  dev_network:
    external: true
