version: '3.7'
 
services:
  elasticsearch:
    image: elasticsearch:8.4.1
    container_name: elasticsearch-service
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - dev_network
  kibana:
    image: kibana:8.4.1
    container_name: kibana-service
    environment:
      # - ELASTICSEARCH_USERNAME=elastic
      # - ELASTICSEARCH_PASSWORD=changeme
      - ELASTICSEARCH_URL=http://elasticsearch-service:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch-service:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - dev_network


  logstash:
    image: logstash:8.4.1
    ports:
      - "25826:25826"
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro                # Pipeline configuration
    # restart: on-failure
    depends_on:
      - elasticsearch
    networks:
      - dev_network

  filebeat:
    image: elastic/filebeat:8.4.1
    volumes:
      - ./filebeat//filebeat.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
      - ./filebeat/data:/usr/share/filebeat/data:rw                        # Persistence data
    user: root                                                             # Allow access to log files and docker.sock
    # restart: on-failure
    depends_on:
      - logstash
    networks:
      - dev_network
    command:
      - "-e"
      - "--strict.perms=false"

volumes:
  elasticsearch-data:
    driver: local

networks:
  dev_network:
    external: true