version: '3.7'

services:

  gateway-service:
    build:
      context: ../gateway-service
      dockerfile: Dockerfile
    networks:
      -   dev_network
    ports:
      - 8081:8081

  professor-service:
    build:
      context: ../professor-service
      dockerfile: Dockerfile
    networks:
      - dev_network
    depends_on:
      - gateway-service
  
  student-service:
    build:
      context: ../student-service
      dockerfile: Dockerfile
    networks:
      - dev_network

    depends_on:
      - gateway-service

  evaluation-service:
    build:
      context: ../evaluation-service
      dockerfile: Dockerfile
    networks:
      - dev_network

    depends_on:
      - gateway-service

  notification-service:
    build:
      context: ../notification-service
      dockerfile: Dockerfile
    networks:
      - dev_network

    depends_on:
      - gateway-service

  course-service:
    build:
      context: ../course-service
      dockerfile: Dockerfile
    networks:
      - dev_network

    depends_on:
      - gateway-service
      
networks:
  dev_network:
    external: true
     


      