spring:
  application:
    name: service-registry
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8080/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    hostname: eureka-server
  wait-time-in-ms-when-sync-empty: 0



