spring:
  application:
    name: service-registry
  zipkin:
    base-url: http://localhost:9411



server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    hostname: localhost
  wait-time-in-ms-when-sync-empty: 0



