spring:
  application:
    name: service-registry



server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    hostname:
  wait-time-in-ms-when-sync-empty: 0

---
spring:
  application:
    name: service-registry
  profiles:
    active: docker


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8080/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    hostname:
  wait-time-in-ms-when-sync-empty: 0

