spring:
  application:
    name: evaluation-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks
      client:
        registration:
          ikub-client:
            provider: spring
            client-id: ikub
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          spring:
            issuer-uri: http://localhost:9000
  zipkin:
    base-url: http://localhost:9411
  kafka:
    client-id: ${spring.application.name}
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: Notification:com.evaluation.model.Notification

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
server:
  port: 8086

resource:
  studentService:
    baseUrl: http://localhost:8084/student
kafkaTopics:
  notification: notifications

swagger.server.uri: http://localhost:8081/evaluation-service