spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  zipkin:
    base-url: http://localhost:9411
  cloud:
    config:
      enabled: true
    gateway:
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student-service/**
          filters:
            - StripPrefix=1
        - id: professor-service
          uri: lb://professor-service
          predicates:
            - Path=/professor-service/**
          filters:
            - StripPrefix=1
        - id: evaluation-service
          uri: lb://evaluation-service
          predicates:
            - Path=/evaluation-service/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/**
          filters:
            - StripPrefix=1
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/course-service/**
          filters:
            - StripPrefix=1

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus
springdoc:
  swagger-ui:
    urls:
      - name: "Course Service APIs"
        url: "/course-service/v3/api-docs"
      - name: "Professor Service APIs"
        url: "/professor-service/v3/api-docs"
      - name: "Student Service APIs"
        url: "/student-service/v3/api-docs"
      - name: "Evaluation Service APIs"
        url: "/evaluation-service/v3/api-docs"
      - name: "Notification Service APIs"
        url: "/notification-service/v3/api-docs"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
server:
  port: 8081