spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
  zipkin:
    base-url: http://localhost:9411

  cloud:
    config:
      enabled: true
    gateway:
      routes:
        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/application-service/**
          filters:
            - StripPrefix=1


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
server:
  port: 8081



---

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
  zipkin:
    base-url: http://zipkin:9411
  profiles:
    active: docker

  cloud:
    config:
      enabled: true
    gateway:
      routes:
        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/application-service/**
          filters:
            - StripPrefix=1



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
server:
  port: 8081