
spring:
  application:
    name: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
  cloud:
    config:
      enabled: true
    function:
      definition: sendNotification
    stream:
      kafka:
        binder:
          brokers: kafka:9092
        bindings:
          sendNotification-in-0:
            consumer:
              configuration:
                value.deserializer: com.notification.model.converters.NotificationDeserializer
      bindings:
        sendNotification-in-0:
          destination: notifications
          consumer:
            use-native-decoding: true
  zipkin:
    base-url: http://zipkin:9411

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8080/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: eureka-server
    prefer-ip-address: true
server:
  port: 8082

swagger.server.uri: http://host.docker.internal:8081/notification-service