
spring:
  application:
    name: professor-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
  zipkin:
    base-url: http://zipkin:9411
#  profiles:
#    active: docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8080/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: eureka-server
    prefer-ip-address: true
server:
  port: 8083